version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "api_main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - mynetwork

  updater:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "/app/updater_main.py"]
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      #- ./mongod.conf:/etc/mongod.conf
      - mongo-data:/data/db
    networks:
      - mynetwork
    #command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]

volumes:
  mongo-data:

networks:
  mynetwork:
    driver: bridge