version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "api_main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  updater:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "/app/updater_main.py"]
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
